name: Bedford Lab Research
description: Science updates on evolution, epidemiology and immunology from the Bedford lab at the Fred Hutch
url: http://bedford.io

markdown: redcarpet
permalink: /:categories/:title/
future: true

redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

exclude:
  - "*.class"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.nb"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.branches"
  - "*.csv"
  - "*.fasta"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.newick"
  - "*.nex"
  - "*.tsv"
  - "*.tips"
  - "*.trees"
  - "*.txt"
  - "*.zip"
  - "*.gz"    
  - "Gemfile"
  - "Gemfile.lock"
  - "projects/nextflu/auspice/index.html"
  - "projects/nextflu/auspice/css/*"
  - "projects/nextflu/auspice/h3n2/*"
  - "projects/nextflu/auspice/h1n1pdm/*"
  - "projects/nextflu/auspice/vic/*"
  - "projects/nextflu/auspice/yam/*"
  - "projects/nextflu/auspice/zika/*"
  - "projects/nextflu/auspice/zibra/*"
  - "projects/nextflu/auspice/muttree/*"
  - "projects/nextflu/auspice/reports/*"
  - "projects/nextflu/auspice/js/*"
  - "projects/auspice/src/*"
  - "projects/siv-cst/beast/main/empiricalTrees/xml/*"
  - "projects/siv-cst/beast/supplement/discreteTraits/xml/*"
  - "projects/siv-cst/beast/supplement/empiricalTrees/xml/*"

projects:
  - trvrb/coaltrace
  - trvrb/stem
  - trvrb/PACT
  - trvrb/dynamics-practical
  - trvrb/antigen
  - trvrb/haplotypes
  - trvrb/divergence
  - trvrb/ancestry
  - trvrb/medium-data
  - trvrb/flutrace
  - blab/nextflu
  - alvason/infectious-pulse
  - blab/global-migration
  - trvrb/sismid
  - trvrb/sctrace
  - trvrb/phylodynamics-lecture
  - blab/baltic
  - blab/chikv
  - blab/yellow-fever
  - blab/unsampled
  - nextstrain/fauna
  - nextstrain/augur
  - nextstrain/auspice
  - blab/zika-seq
  - blab/siv-cst
